server:
  port: 8080

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:notification_audit;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
